lanague: objective-c

sx_image: xcode7.1
script: - xcodebuild -project KSGallerySlidingCollectionViewDemo/KSGallerySlidingCollectionView.xcodeproj -target KSGallerySlidingCollectionView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

